/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SistemaRouteImport } from './routes/_sistema'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SistemaTutorialRouteImport } from './routes/_sistema.tutorial'
import { Route as SistemaStatusDocumentosRouteImport } from './routes/_sistema.status-documentos'
import { Route as SistemaPerfilRouteImport } from './routes/_sistema.perfil'
import { Route as SistemaDiarioOficialRouteImport } from './routes/_sistema.diario-oficial'
import { Route as SistemaDashboardRouteImport } from './routes/_sistema.dashboard'
import { Route as SistemaAcompanhamentoRouteImport } from './routes/_sistema.acompanhamento'
import { Route as SistemaAcervoRouteImport } from './routes/_sistema.acervo'
import { Route as AuthRegistroRouteImport } from './routes/_auth.registro'
import { Route as AuthOnboardingRouteImport } from './routes/_auth.onboarding'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthAguardandoRouteImport } from './routes/_auth.aguardando'
import { Route as SistemaRevisaoTodasRouteImport } from './routes/_sistema.revisao.todas'
import { Route as SistemaRevisaoMinhasRouteImport } from './routes/_sistema.revisao.minhas'
import { Route as SistemaRevisaoFilaRouteImport } from './routes/_sistema.revisao.fila'
import { Route as SistemaDiarioOficialGuiaRouteImport } from './routes/_sistema.diario-oficial.guia'
import { Route as SistemaAdminVariaveisDicasRouteImport } from './routes/_sistema.admin.variaveis-dicas'
import { Route as SistemaAdminVariaveisRouteImport } from './routes/_sistema.admin.variaveis'
import { Route as SistemaAdminUsuariosOrgaoRouteImport } from './routes/_sistema.admin.usuarios-orgao'
import { Route as SistemaAdminUsuariosRouteImport } from './routes/_sistema.admin.usuarios'
import { Route as SistemaAdminOrganogramaRouteImport } from './routes/_sistema.admin.organograma'
import { Route as SistemaAdminModelosRouteImport } from './routes/_sistema.admin.modelos'
import { Route as SistemaAdminLogsRouteImport } from './routes/_sistema.admin.logs'
import { Route as SistemaAdminLlmRouteImport } from './routes/_sistema.admin.llm'
import { Route as SistemaAdminLivrosRouteImport } from './routes/_sistema.admin.livros'
import { Route as SistemaAdminIntegracoesRouteImport } from './routes/_sistema.admin.integracoes'
import { Route as SistemaAdminIaRouteImport } from './routes/_sistema.admin.ia'
import { Route as SistemaAdminGestaoRouteImport } from './routes/_sistema.admin.gestao'
import { Route as SistemaAdminFilaAprovacaoRouteImport } from './routes/_sistema.admin.fila-aprovacao'
import { Route as SistemaAdminCloudconvertRouteImport } from './routes/_sistema.admin.cloudconvert'
import { Route as SistemaAdminAnalyticsAvancadoRouteImport } from './routes/_sistema.admin.analytics-avancado'
import { Route as SistemaAdminAnalyticsRouteImport } from './routes/_sistema.admin.analytics'
import { Route as SistemaAdministrativoPortariasIndexRouteImport } from './routes/_sistema.administrativo.portarias.index'
import { Route as SistemaAdminUsuariosIndexRouteImport } from './routes/_sistema.admin.usuarios.index'
import { Route as SistemaAdministrativoPortariasNovoRouteImport } from './routes/_sistema.administrativo.portarias.novo'
import { Route as SistemaAdministrativoPortariasIdRouteImport } from './routes/_sistema.administrativo.portarias.$id'
import { Route as SistemaAdminUsuariosUsuarioIdRouteImport } from './routes/_sistema.admin.usuarios.$usuarioId'
import { Route as SistemaAdminModelosTutorialRouteImport } from './routes/_sistema.admin.modelos.tutorial'
import { Route as SistemaAdminModelosNovoRouteImport } from './routes/_sistema.admin.modelos.novo'
import { Route as SistemaAdminModelosIdRouteImport } from './routes/_sistema.admin.modelos.$id'
import { Route as SistemaAdministrativoPortariasRevisaoIdRouteImport } from './routes/_sistema.administrativo.portarias.revisao.$id'

const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/_sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaTutorialRoute = SistemaTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaStatusDocumentosRoute = SistemaStatusDocumentosRouteImport.update({
  id: '/status-documentos',
  path: '/status-documentos',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaPerfilRoute = SistemaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaDiarioOficialRoute = SistemaDiarioOficialRouteImport.update({
  id: '/diario-oficial',
  path: '/diario-oficial',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaDashboardRoute = SistemaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAcompanhamentoRoute = SistemaAcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAcervoRoute = SistemaAcervoRouteImport.update({
  id: '/acervo',
  path: '/acervo',
  getParentRoute: () => SistemaRoute,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAguardandoRoute = AuthAguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => AuthRoute,
} as any)
const SistemaRevisaoTodasRoute = SistemaRevisaoTodasRouteImport.update({
  id: '/revisao/todas',
  path: '/revisao/todas',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaRevisaoMinhasRoute = SistemaRevisaoMinhasRouteImport.update({
  id: '/revisao/minhas',
  path: '/revisao/minhas',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaRevisaoFilaRoute = SistemaRevisaoFilaRouteImport.update({
  id: '/revisao/fila',
  path: '/revisao/fila',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaDiarioOficialGuiaRoute =
  SistemaDiarioOficialGuiaRouteImport.update({
    id: '/guia',
    path: '/guia',
    getParentRoute: () => SistemaDiarioOficialRoute,
  } as any)
const SistemaAdminVariaveisDicasRoute =
  SistemaAdminVariaveisDicasRouteImport.update({
    id: '/admin/variaveis-dicas',
    path: '/admin/variaveis-dicas',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminVariaveisRoute = SistemaAdminVariaveisRouteImport.update({
  id: '/admin/variaveis',
  path: '/admin/variaveis',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminUsuariosOrgaoRoute =
  SistemaAdminUsuariosOrgaoRouteImport.update({
    id: '/admin/usuarios-orgao',
    path: '/admin/usuarios-orgao',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminUsuariosRoute = SistemaAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminOrganogramaRoute = SistemaAdminOrganogramaRouteImport.update({
  id: '/admin/organograma',
  path: '/admin/organograma',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminModelosRoute = SistemaAdminModelosRouteImport.update({
  id: '/admin/modelos',
  path: '/admin/modelos',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminLogsRoute = SistemaAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminLlmRoute = SistemaAdminLlmRouteImport.update({
  id: '/admin/llm',
  path: '/admin/llm',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminLivrosRoute = SistemaAdminLivrosRouteImport.update({
  id: '/admin/livros',
  path: '/admin/livros',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminIntegracoesRoute = SistemaAdminIntegracoesRouteImport.update({
  id: '/admin/integracoes',
  path: '/admin/integracoes',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminIaRoute = SistemaAdminIaRouteImport.update({
  id: '/admin/ia',
  path: '/admin/ia',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminGestaoRoute = SistemaAdminGestaoRouteImport.update({
  id: '/admin/gestao',
  path: '/admin/gestao',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdminFilaAprovacaoRoute =
  SistemaAdminFilaAprovacaoRouteImport.update({
    id: '/admin/fila-aprovacao',
    path: '/admin/fila-aprovacao',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminCloudconvertRoute =
  SistemaAdminCloudconvertRouteImport.update({
    id: '/admin/cloudconvert',
    path: '/admin/cloudconvert',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminAnalyticsAvancadoRoute =
  SistemaAdminAnalyticsAvancadoRouteImport.update({
    id: '/admin/analytics-avancado',
    path: '/admin/analytics-avancado',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminAnalyticsRoute = SistemaAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => SistemaRoute,
} as any)
const SistemaAdministrativoPortariasIndexRoute =
  SistemaAdministrativoPortariasIndexRouteImport.update({
    id: '/administrativo/portarias/',
    path: '/administrativo/portarias/',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminUsuariosIndexRoute =
  SistemaAdminUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SistemaAdminUsuariosRoute,
  } as any)
const SistemaAdministrativoPortariasNovoRoute =
  SistemaAdministrativoPortariasNovoRouteImport.update({
    id: '/administrativo/portarias/novo',
    path: '/administrativo/portarias/novo',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdministrativoPortariasIdRoute =
  SistemaAdministrativoPortariasIdRouteImport.update({
    id: '/administrativo/portarias/$id',
    path: '/administrativo/portarias/$id',
    getParentRoute: () => SistemaRoute,
  } as any)
const SistemaAdminUsuariosUsuarioIdRoute =
  SistemaAdminUsuariosUsuarioIdRouteImport.update({
    id: '/$usuarioId',
    path: '/$usuarioId',
    getParentRoute: () => SistemaAdminUsuariosRoute,
  } as any)
const SistemaAdminModelosTutorialRoute =
  SistemaAdminModelosTutorialRouteImport.update({
    id: '/tutorial',
    path: '/tutorial',
    getParentRoute: () => SistemaAdminModelosRoute,
  } as any)
const SistemaAdminModelosNovoRoute = SistemaAdminModelosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => SistemaAdminModelosRoute,
} as any)
const SistemaAdminModelosIdRoute = SistemaAdminModelosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SistemaAdminModelosRoute,
} as any)
const SistemaAdministrativoPortariasRevisaoIdRoute =
  SistemaAdministrativoPortariasRevisaoIdRouteImport.update({
    id: '/administrativo/portarias/revisao/$id',
    path: '/administrativo/portarias/revisao/$id',
    getParentRoute: () => SistemaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SistemaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/aguardando': typeof AuthAguardandoRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/registro': typeof AuthRegistroRoute
  '/acervo': typeof SistemaAcervoRoute
  '/acompanhamento': typeof SistemaAcompanhamentoRoute
  '/dashboard': typeof SistemaDashboardRoute
  '/diario-oficial': typeof SistemaDiarioOficialRouteWithChildren
  '/perfil': typeof SistemaPerfilRoute
  '/status-documentos': typeof SistemaStatusDocumentosRoute
  '/tutorial': typeof SistemaTutorialRoute
  '/admin/analytics': typeof SistemaAdminAnalyticsRoute
  '/admin/analytics-avancado': typeof SistemaAdminAnalyticsAvancadoRoute
  '/admin/cloudconvert': typeof SistemaAdminCloudconvertRoute
  '/admin/fila-aprovacao': typeof SistemaAdminFilaAprovacaoRoute
  '/admin/gestao': typeof SistemaAdminGestaoRoute
  '/admin/ia': typeof SistemaAdminIaRoute
  '/admin/integracoes': typeof SistemaAdminIntegracoesRoute
  '/admin/livros': typeof SistemaAdminLivrosRoute
  '/admin/llm': typeof SistemaAdminLlmRoute
  '/admin/logs': typeof SistemaAdminLogsRoute
  '/admin/modelos': typeof SistemaAdminModelosRouteWithChildren
  '/admin/organograma': typeof SistemaAdminOrganogramaRoute
  '/admin/usuarios': typeof SistemaAdminUsuariosRouteWithChildren
  '/admin/usuarios-orgao': typeof SistemaAdminUsuariosOrgaoRoute
  '/admin/variaveis': typeof SistemaAdminVariaveisRoute
  '/admin/variaveis-dicas': typeof SistemaAdminVariaveisDicasRoute
  '/diario-oficial/guia': typeof SistemaDiarioOficialGuiaRoute
  '/revisao/fila': typeof SistemaRevisaoFilaRoute
  '/revisao/minhas': typeof SistemaRevisaoMinhasRoute
  '/revisao/todas': typeof SistemaRevisaoTodasRoute
  '/admin/modelos/$id': typeof SistemaAdminModelosIdRoute
  '/admin/modelos/novo': typeof SistemaAdminModelosNovoRoute
  '/admin/modelos/tutorial': typeof SistemaAdminModelosTutorialRoute
  '/admin/usuarios/$usuarioId': typeof SistemaAdminUsuariosUsuarioIdRoute
  '/administrativo/portarias/$id': typeof SistemaAdministrativoPortariasIdRoute
  '/administrativo/portarias/novo': typeof SistemaAdministrativoPortariasNovoRoute
  '/admin/usuarios/': typeof SistemaAdminUsuariosIndexRoute
  '/administrativo/portarias/': typeof SistemaAdministrativoPortariasIndexRoute
  '/administrativo/portarias/revisao/$id': typeof SistemaAdministrativoPortariasRevisaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof SistemaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/aguardando': typeof AuthAguardandoRoute
  '/login': typeof AuthLoginRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/registro': typeof AuthRegistroRoute
  '/acervo': typeof SistemaAcervoRoute
  '/acompanhamento': typeof SistemaAcompanhamentoRoute
  '/dashboard': typeof SistemaDashboardRoute
  '/diario-oficial': typeof SistemaDiarioOficialRouteWithChildren
  '/perfil': typeof SistemaPerfilRoute
  '/status-documentos': typeof SistemaStatusDocumentosRoute
  '/tutorial': typeof SistemaTutorialRoute
  '/admin/analytics': typeof SistemaAdminAnalyticsRoute
  '/admin/analytics-avancado': typeof SistemaAdminAnalyticsAvancadoRoute
  '/admin/cloudconvert': typeof SistemaAdminCloudconvertRoute
  '/admin/fila-aprovacao': typeof SistemaAdminFilaAprovacaoRoute
  '/admin/gestao': typeof SistemaAdminGestaoRoute
  '/admin/ia': typeof SistemaAdminIaRoute
  '/admin/integracoes': typeof SistemaAdminIntegracoesRoute
  '/admin/livros': typeof SistemaAdminLivrosRoute
  '/admin/llm': typeof SistemaAdminLlmRoute
  '/admin/logs': typeof SistemaAdminLogsRoute
  '/admin/modelos': typeof SistemaAdminModelosRouteWithChildren
  '/admin/organograma': typeof SistemaAdminOrganogramaRoute
  '/admin/usuarios-orgao': typeof SistemaAdminUsuariosOrgaoRoute
  '/admin/variaveis': typeof SistemaAdminVariaveisRoute
  '/admin/variaveis-dicas': typeof SistemaAdminVariaveisDicasRoute
  '/diario-oficial/guia': typeof SistemaDiarioOficialGuiaRoute
  '/revisao/fila': typeof SistemaRevisaoFilaRoute
  '/revisao/minhas': typeof SistemaRevisaoMinhasRoute
  '/revisao/todas': typeof SistemaRevisaoTodasRoute
  '/admin/modelos/$id': typeof SistemaAdminModelosIdRoute
  '/admin/modelos/novo': typeof SistemaAdminModelosNovoRoute
  '/admin/modelos/tutorial': typeof SistemaAdminModelosTutorialRoute
  '/admin/usuarios/$usuarioId': typeof SistemaAdminUsuariosUsuarioIdRoute
  '/administrativo/portarias/$id': typeof SistemaAdministrativoPortariasIdRoute
  '/administrativo/portarias/novo': typeof SistemaAdministrativoPortariasNovoRoute
  '/admin/usuarios': typeof SistemaAdminUsuariosIndexRoute
  '/administrativo/portarias': typeof SistemaAdministrativoPortariasIndexRoute
  '/administrativo/portarias/revisao/$id': typeof SistemaAdministrativoPortariasRevisaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_sistema': typeof SistemaRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/_auth/aguardando': typeof AuthAguardandoRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_auth/registro': typeof AuthRegistroRoute
  '/_sistema/acervo': typeof SistemaAcervoRoute
  '/_sistema/acompanhamento': typeof SistemaAcompanhamentoRoute
  '/_sistema/dashboard': typeof SistemaDashboardRoute
  '/_sistema/diario-oficial': typeof SistemaDiarioOficialRouteWithChildren
  '/_sistema/perfil': typeof SistemaPerfilRoute
  '/_sistema/status-documentos': typeof SistemaStatusDocumentosRoute
  '/_sistema/tutorial': typeof SistemaTutorialRoute
  '/_sistema/admin/analytics': typeof SistemaAdminAnalyticsRoute
  '/_sistema/admin/analytics-avancado': typeof SistemaAdminAnalyticsAvancadoRoute
  '/_sistema/admin/cloudconvert': typeof SistemaAdminCloudconvertRoute
  '/_sistema/admin/fila-aprovacao': typeof SistemaAdminFilaAprovacaoRoute
  '/_sistema/admin/gestao': typeof SistemaAdminGestaoRoute
  '/_sistema/admin/ia': typeof SistemaAdminIaRoute
  '/_sistema/admin/integracoes': typeof SistemaAdminIntegracoesRoute
  '/_sistema/admin/livros': typeof SistemaAdminLivrosRoute
  '/_sistema/admin/llm': typeof SistemaAdminLlmRoute
  '/_sistema/admin/logs': typeof SistemaAdminLogsRoute
  '/_sistema/admin/modelos': typeof SistemaAdminModelosRouteWithChildren
  '/_sistema/admin/organograma': typeof SistemaAdminOrganogramaRoute
  '/_sistema/admin/usuarios': typeof SistemaAdminUsuariosRouteWithChildren
  '/_sistema/admin/usuarios-orgao': typeof SistemaAdminUsuariosOrgaoRoute
  '/_sistema/admin/variaveis': typeof SistemaAdminVariaveisRoute
  '/_sistema/admin/variaveis-dicas': typeof SistemaAdminVariaveisDicasRoute
  '/_sistema/diario-oficial/guia': typeof SistemaDiarioOficialGuiaRoute
  '/_sistema/revisao/fila': typeof SistemaRevisaoFilaRoute
  '/_sistema/revisao/minhas': typeof SistemaRevisaoMinhasRoute
  '/_sistema/revisao/todas': typeof SistemaRevisaoTodasRoute
  '/_sistema/admin/modelos/$id': typeof SistemaAdminModelosIdRoute
  '/_sistema/admin/modelos/novo': typeof SistemaAdminModelosNovoRoute
  '/_sistema/admin/modelos/tutorial': typeof SistemaAdminModelosTutorialRoute
  '/_sistema/admin/usuarios/$usuarioId': typeof SistemaAdminUsuariosUsuarioIdRoute
  '/_sistema/administrativo/portarias/$id': typeof SistemaAdministrativoPortariasIdRoute
  '/_sistema/administrativo/portarias/novo': typeof SistemaAdministrativoPortariasNovoRoute
  '/_sistema/admin/usuarios/': typeof SistemaAdminUsuariosIndexRoute
  '/_sistema/administrativo/portarias/': typeof SistemaAdministrativoPortariasIndexRoute
  '/_sistema/administrativo/portarias/revisao/$id': typeof SistemaAdministrativoPortariasRevisaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sobre'
    | '/validar'
    | '/aguardando'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/acervo'
    | '/acompanhamento'
    | '/dashboard'
    | '/diario-oficial'
    | '/perfil'
    | '/status-documentos'
    | '/tutorial'
    | '/admin/analytics'
    | '/admin/analytics-avancado'
    | '/admin/cloudconvert'
    | '/admin/fila-aprovacao'
    | '/admin/gestao'
    | '/admin/ia'
    | '/admin/integracoes'
    | '/admin/livros'
    | '/admin/llm'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/organograma'
    | '/admin/usuarios'
    | '/admin/usuarios-orgao'
    | '/admin/variaveis'
    | '/admin/variaveis-dicas'
    | '/diario-oficial/guia'
    | '/revisao/fila'
    | '/revisao/minhas'
    | '/revisao/todas'
    | '/admin/modelos/$id'
    | '/admin/modelos/novo'
    | '/admin/modelos/tutorial'
    | '/admin/usuarios/$usuarioId'
    | '/administrativo/portarias/$id'
    | '/administrativo/portarias/novo'
    | '/admin/usuarios/'
    | '/administrativo/portarias/'
    | '/administrativo/portarias/revisao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sobre'
    | '/validar'
    | '/aguardando'
    | '/login'
    | '/onboarding'
    | '/registro'
    | '/acervo'
    | '/acompanhamento'
    | '/dashboard'
    | '/diario-oficial'
    | '/perfil'
    | '/status-documentos'
    | '/tutorial'
    | '/admin/analytics'
    | '/admin/analytics-avancado'
    | '/admin/cloudconvert'
    | '/admin/fila-aprovacao'
    | '/admin/gestao'
    | '/admin/ia'
    | '/admin/integracoes'
    | '/admin/livros'
    | '/admin/llm'
    | '/admin/logs'
    | '/admin/modelos'
    | '/admin/organograma'
    | '/admin/usuarios-orgao'
    | '/admin/variaveis'
    | '/admin/variaveis-dicas'
    | '/diario-oficial/guia'
    | '/revisao/fila'
    | '/revisao/minhas'
    | '/revisao/todas'
    | '/admin/modelos/$id'
    | '/admin/modelos/novo'
    | '/admin/modelos/tutorial'
    | '/admin/usuarios/$usuarioId'
    | '/administrativo/portarias/$id'
    | '/administrativo/portarias/novo'
    | '/admin/usuarios'
    | '/administrativo/portarias'
    | '/administrativo/portarias/revisao/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_sistema'
    | '/sobre'
    | '/validar'
    | '/_auth/aguardando'
    | '/_auth/login'
    | '/_auth/onboarding'
    | '/_auth/registro'
    | '/_sistema/acervo'
    | '/_sistema/acompanhamento'
    | '/_sistema/dashboard'
    | '/_sistema/diario-oficial'
    | '/_sistema/perfil'
    | '/_sistema/status-documentos'
    | '/_sistema/tutorial'
    | '/_sistema/admin/analytics'
    | '/_sistema/admin/analytics-avancado'
    | '/_sistema/admin/cloudconvert'
    | '/_sistema/admin/fila-aprovacao'
    | '/_sistema/admin/gestao'
    | '/_sistema/admin/ia'
    | '/_sistema/admin/integracoes'
    | '/_sistema/admin/livros'
    | '/_sistema/admin/llm'
    | '/_sistema/admin/logs'
    | '/_sistema/admin/modelos'
    | '/_sistema/admin/organograma'
    | '/_sistema/admin/usuarios'
    | '/_sistema/admin/usuarios-orgao'
    | '/_sistema/admin/variaveis'
    | '/_sistema/admin/variaveis-dicas'
    | '/_sistema/diario-oficial/guia'
    | '/_sistema/revisao/fila'
    | '/_sistema/revisao/minhas'
    | '/_sistema/revisao/todas'
    | '/_sistema/admin/modelos/$id'
    | '/_sistema/admin/modelos/novo'
    | '/_sistema/admin/modelos/tutorial'
    | '/_sistema/admin/usuarios/$usuarioId'
    | '/_sistema/administrativo/portarias/$id'
    | '/_sistema/administrativo/portarias/novo'
    | '/_sistema/admin/usuarios/'
    | '/_sistema/administrativo/portarias/'
    | '/_sistema/administrativo/portarias/revisao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SistemaRoute: typeof SistemaRouteWithChildren
  SobreRoute: typeof SobreRoute
  ValidarRoute: typeof ValidarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sistema': {
      id: '/_sistema'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sistema/tutorial': {
      id: '/_sistema/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof SistemaTutorialRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/status-documentos': {
      id: '/_sistema/status-documentos'
      path: '/status-documentos'
      fullPath: '/status-documentos'
      preLoaderRoute: typeof SistemaStatusDocumentosRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/perfil': {
      id: '/_sistema/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof SistemaPerfilRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/diario-oficial': {
      id: '/_sistema/diario-oficial'
      path: '/diario-oficial'
      fullPath: '/diario-oficial'
      preLoaderRoute: typeof SistemaDiarioOficialRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/dashboard': {
      id: '/_sistema/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SistemaDashboardRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/acompanhamento': {
      id: '/_sistema/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof SistemaAcompanhamentoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/acervo': {
      id: '/_sistema/acervo'
      path: '/acervo'
      fullPath: '/acervo'
      preLoaderRoute: typeof SistemaAcervoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_auth/registro': {
      id: '/_auth/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/aguardando': {
      id: '/_auth/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AuthAguardandoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_sistema/revisao/todas': {
      id: '/_sistema/revisao/todas'
      path: '/revisao/todas'
      fullPath: '/revisao/todas'
      preLoaderRoute: typeof SistemaRevisaoTodasRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/revisao/minhas': {
      id: '/_sistema/revisao/minhas'
      path: '/revisao/minhas'
      fullPath: '/revisao/minhas'
      preLoaderRoute: typeof SistemaRevisaoMinhasRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/revisao/fila': {
      id: '/_sistema/revisao/fila'
      path: '/revisao/fila'
      fullPath: '/revisao/fila'
      preLoaderRoute: typeof SistemaRevisaoFilaRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/diario-oficial/guia': {
      id: '/_sistema/diario-oficial/guia'
      path: '/guia'
      fullPath: '/diario-oficial/guia'
      preLoaderRoute: typeof SistemaDiarioOficialGuiaRouteImport
      parentRoute: typeof SistemaDiarioOficialRoute
    }
    '/_sistema/admin/variaveis-dicas': {
      id: '/_sistema/admin/variaveis-dicas'
      path: '/admin/variaveis-dicas'
      fullPath: '/admin/variaveis-dicas'
      preLoaderRoute: typeof SistemaAdminVariaveisDicasRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/variaveis': {
      id: '/_sistema/admin/variaveis'
      path: '/admin/variaveis'
      fullPath: '/admin/variaveis'
      preLoaderRoute: typeof SistemaAdminVariaveisRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/usuarios-orgao': {
      id: '/_sistema/admin/usuarios-orgao'
      path: '/admin/usuarios-orgao'
      fullPath: '/admin/usuarios-orgao'
      preLoaderRoute: typeof SistemaAdminUsuariosOrgaoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/usuarios': {
      id: '/_sistema/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof SistemaAdminUsuariosRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/organograma': {
      id: '/_sistema/admin/organograma'
      path: '/admin/organograma'
      fullPath: '/admin/organograma'
      preLoaderRoute: typeof SistemaAdminOrganogramaRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/modelos': {
      id: '/_sistema/admin/modelos'
      path: '/admin/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof SistemaAdminModelosRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/logs': {
      id: '/_sistema/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof SistemaAdminLogsRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/llm': {
      id: '/_sistema/admin/llm'
      path: '/admin/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof SistemaAdminLlmRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/livros': {
      id: '/_sistema/admin/livros'
      path: '/admin/livros'
      fullPath: '/admin/livros'
      preLoaderRoute: typeof SistemaAdminLivrosRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/integracoes': {
      id: '/_sistema/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof SistemaAdminIntegracoesRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/ia': {
      id: '/_sistema/admin/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof SistemaAdminIaRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/gestao': {
      id: '/_sistema/admin/gestao'
      path: '/admin/gestao'
      fullPath: '/admin/gestao'
      preLoaderRoute: typeof SistemaAdminGestaoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/fila-aprovacao': {
      id: '/_sistema/admin/fila-aprovacao'
      path: '/admin/fila-aprovacao'
      fullPath: '/admin/fila-aprovacao'
      preLoaderRoute: typeof SistemaAdminFilaAprovacaoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/cloudconvert': {
      id: '/_sistema/admin/cloudconvert'
      path: '/admin/cloudconvert'
      fullPath: '/admin/cloudconvert'
      preLoaderRoute: typeof SistemaAdminCloudconvertRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/analytics-avancado': {
      id: '/_sistema/admin/analytics-avancado'
      path: '/admin/analytics-avancado'
      fullPath: '/admin/analytics-avancado'
      preLoaderRoute: typeof SistemaAdminAnalyticsAvancadoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/analytics': {
      id: '/_sistema/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof SistemaAdminAnalyticsRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/administrativo/portarias/': {
      id: '/_sistema/administrativo/portarias/'
      path: '/administrativo/portarias'
      fullPath: '/administrativo/portarias/'
      preLoaderRoute: typeof SistemaAdministrativoPortariasIndexRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/usuarios/': {
      id: '/_sistema/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof SistemaAdminUsuariosIndexRouteImport
      parentRoute: typeof SistemaAdminUsuariosRoute
    }
    '/_sistema/administrativo/portarias/novo': {
      id: '/_sistema/administrativo/portarias/novo'
      path: '/administrativo/portarias/novo'
      fullPath: '/administrativo/portarias/novo'
      preLoaderRoute: typeof SistemaAdministrativoPortariasNovoRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/administrativo/portarias/$id': {
      id: '/_sistema/administrativo/portarias/$id'
      path: '/administrativo/portarias/$id'
      fullPath: '/administrativo/portarias/$id'
      preLoaderRoute: typeof SistemaAdministrativoPortariasIdRouteImport
      parentRoute: typeof SistemaRoute
    }
    '/_sistema/admin/usuarios/$usuarioId': {
      id: '/_sistema/admin/usuarios/$usuarioId'
      path: '/$usuarioId'
      fullPath: '/admin/usuarios/$usuarioId'
      preLoaderRoute: typeof SistemaAdminUsuariosUsuarioIdRouteImport
      parentRoute: typeof SistemaAdminUsuariosRoute
    }
    '/_sistema/admin/modelos/tutorial': {
      id: '/_sistema/admin/modelos/tutorial'
      path: '/tutorial'
      fullPath: '/admin/modelos/tutorial'
      preLoaderRoute: typeof SistemaAdminModelosTutorialRouteImport
      parentRoute: typeof SistemaAdminModelosRoute
    }
    '/_sistema/admin/modelos/novo': {
      id: '/_sistema/admin/modelos/novo'
      path: '/novo'
      fullPath: '/admin/modelos/novo'
      preLoaderRoute: typeof SistemaAdminModelosNovoRouteImport
      parentRoute: typeof SistemaAdminModelosRoute
    }
    '/_sistema/admin/modelos/$id': {
      id: '/_sistema/admin/modelos/$id'
      path: '/$id'
      fullPath: '/admin/modelos/$id'
      preLoaderRoute: typeof SistemaAdminModelosIdRouteImport
      parentRoute: typeof SistemaAdminModelosRoute
    }
    '/_sistema/administrativo/portarias/revisao/$id': {
      id: '/_sistema/administrativo/portarias/revisao/$id'
      path: '/administrativo/portarias/revisao/$id'
      fullPath: '/administrativo/portarias/revisao/$id'
      preLoaderRoute: typeof SistemaAdministrativoPortariasRevisaoIdRouteImport
      parentRoute: typeof SistemaRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAguardandoRoute: typeof AuthAguardandoRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAguardandoRoute: AuthAguardandoRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthRegistroRoute: AuthRegistroRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SistemaDiarioOficialRouteChildren {
  SistemaDiarioOficialGuiaRoute: typeof SistemaDiarioOficialGuiaRoute
}

const SistemaDiarioOficialRouteChildren: SistemaDiarioOficialRouteChildren = {
  SistemaDiarioOficialGuiaRoute: SistemaDiarioOficialGuiaRoute,
}

const SistemaDiarioOficialRouteWithChildren =
  SistemaDiarioOficialRoute._addFileChildren(SistemaDiarioOficialRouteChildren)

interface SistemaAdminModelosRouteChildren {
  SistemaAdminModelosIdRoute: typeof SistemaAdminModelosIdRoute
  SistemaAdminModelosNovoRoute: typeof SistemaAdminModelosNovoRoute
  SistemaAdminModelosTutorialRoute: typeof SistemaAdminModelosTutorialRoute
}

const SistemaAdminModelosRouteChildren: SistemaAdminModelosRouteChildren = {
  SistemaAdminModelosIdRoute: SistemaAdminModelosIdRoute,
  SistemaAdminModelosNovoRoute: SistemaAdminModelosNovoRoute,
  SistemaAdminModelosTutorialRoute: SistemaAdminModelosTutorialRoute,
}

const SistemaAdminModelosRouteWithChildren =
  SistemaAdminModelosRoute._addFileChildren(SistemaAdminModelosRouteChildren)

interface SistemaAdminUsuariosRouteChildren {
  SistemaAdminUsuariosUsuarioIdRoute: typeof SistemaAdminUsuariosUsuarioIdRoute
  SistemaAdminUsuariosIndexRoute: typeof SistemaAdminUsuariosIndexRoute
}

const SistemaAdminUsuariosRouteChildren: SistemaAdminUsuariosRouteChildren = {
  SistemaAdminUsuariosUsuarioIdRoute: SistemaAdminUsuariosUsuarioIdRoute,
  SistemaAdminUsuariosIndexRoute: SistemaAdminUsuariosIndexRoute,
}

const SistemaAdminUsuariosRouteWithChildren =
  SistemaAdminUsuariosRoute._addFileChildren(SistemaAdminUsuariosRouteChildren)

interface SistemaRouteChildren {
  SistemaAcervoRoute: typeof SistemaAcervoRoute
  SistemaAcompanhamentoRoute: typeof SistemaAcompanhamentoRoute
  SistemaDashboardRoute: typeof SistemaDashboardRoute
  SistemaDiarioOficialRoute: typeof SistemaDiarioOficialRouteWithChildren
  SistemaPerfilRoute: typeof SistemaPerfilRoute
  SistemaStatusDocumentosRoute: typeof SistemaStatusDocumentosRoute
  SistemaTutorialRoute: typeof SistemaTutorialRoute
  SistemaAdminAnalyticsRoute: typeof SistemaAdminAnalyticsRoute
  SistemaAdminAnalyticsAvancadoRoute: typeof SistemaAdminAnalyticsAvancadoRoute
  SistemaAdminCloudconvertRoute: typeof SistemaAdminCloudconvertRoute
  SistemaAdminFilaAprovacaoRoute: typeof SistemaAdminFilaAprovacaoRoute
  SistemaAdminGestaoRoute: typeof SistemaAdminGestaoRoute
  SistemaAdminIaRoute: typeof SistemaAdminIaRoute
  SistemaAdminIntegracoesRoute: typeof SistemaAdminIntegracoesRoute
  SistemaAdminLivrosRoute: typeof SistemaAdminLivrosRoute
  SistemaAdminLlmRoute: typeof SistemaAdminLlmRoute
  SistemaAdminLogsRoute: typeof SistemaAdminLogsRoute
  SistemaAdminModelosRoute: typeof SistemaAdminModelosRouteWithChildren
  SistemaAdminOrganogramaRoute: typeof SistemaAdminOrganogramaRoute
  SistemaAdminUsuariosRoute: typeof SistemaAdminUsuariosRouteWithChildren
  SistemaAdminUsuariosOrgaoRoute: typeof SistemaAdminUsuariosOrgaoRoute
  SistemaAdminVariaveisRoute: typeof SistemaAdminVariaveisRoute
  SistemaAdminVariaveisDicasRoute: typeof SistemaAdminVariaveisDicasRoute
  SistemaRevisaoFilaRoute: typeof SistemaRevisaoFilaRoute
  SistemaRevisaoMinhasRoute: typeof SistemaRevisaoMinhasRoute
  SistemaRevisaoTodasRoute: typeof SistemaRevisaoTodasRoute
  SistemaAdministrativoPortariasIdRoute: typeof SistemaAdministrativoPortariasIdRoute
  SistemaAdministrativoPortariasNovoRoute: typeof SistemaAdministrativoPortariasNovoRoute
  SistemaAdministrativoPortariasIndexRoute: typeof SistemaAdministrativoPortariasIndexRoute
  SistemaAdministrativoPortariasRevisaoIdRoute: typeof SistemaAdministrativoPortariasRevisaoIdRoute
}

const SistemaRouteChildren: SistemaRouteChildren = {
  SistemaAcervoRoute: SistemaAcervoRoute,
  SistemaAcompanhamentoRoute: SistemaAcompanhamentoRoute,
  SistemaDashboardRoute: SistemaDashboardRoute,
  SistemaDiarioOficialRoute: SistemaDiarioOficialRouteWithChildren,
  SistemaPerfilRoute: SistemaPerfilRoute,
  SistemaStatusDocumentosRoute: SistemaStatusDocumentosRoute,
  SistemaTutorialRoute: SistemaTutorialRoute,
  SistemaAdminAnalyticsRoute: SistemaAdminAnalyticsRoute,
  SistemaAdminAnalyticsAvancadoRoute: SistemaAdminAnalyticsAvancadoRoute,
  SistemaAdminCloudconvertRoute: SistemaAdminCloudconvertRoute,
  SistemaAdminFilaAprovacaoRoute: SistemaAdminFilaAprovacaoRoute,
  SistemaAdminGestaoRoute: SistemaAdminGestaoRoute,
  SistemaAdminIaRoute: SistemaAdminIaRoute,
  SistemaAdminIntegracoesRoute: SistemaAdminIntegracoesRoute,
  SistemaAdminLivrosRoute: SistemaAdminLivrosRoute,
  SistemaAdminLlmRoute: SistemaAdminLlmRoute,
  SistemaAdminLogsRoute: SistemaAdminLogsRoute,
  SistemaAdminModelosRoute: SistemaAdminModelosRouteWithChildren,
  SistemaAdminOrganogramaRoute: SistemaAdminOrganogramaRoute,
  SistemaAdminUsuariosRoute: SistemaAdminUsuariosRouteWithChildren,
  SistemaAdminUsuariosOrgaoRoute: SistemaAdminUsuariosOrgaoRoute,
  SistemaAdminVariaveisRoute: SistemaAdminVariaveisRoute,
  SistemaAdminVariaveisDicasRoute: SistemaAdminVariaveisDicasRoute,
  SistemaRevisaoFilaRoute: SistemaRevisaoFilaRoute,
  SistemaRevisaoMinhasRoute: SistemaRevisaoMinhasRoute,
  SistemaRevisaoTodasRoute: SistemaRevisaoTodasRoute,
  SistemaAdministrativoPortariasIdRoute: SistemaAdministrativoPortariasIdRoute,
  SistemaAdministrativoPortariasNovoRoute:
    SistemaAdministrativoPortariasNovoRoute,
  SistemaAdministrativoPortariasIndexRoute:
    SistemaAdministrativoPortariasIndexRoute,
  SistemaAdministrativoPortariasRevisaoIdRoute:
    SistemaAdministrativoPortariasRevisaoIdRoute,
}

const SistemaRouteWithChildren =
  SistemaRoute._addFileChildren(SistemaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SistemaRoute: SistemaRouteWithChildren,
  SobreRoute: SobreRoute,
  ValidarRoute: ValidarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
