// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // DIRECT_URL (porta 5432, conexão direta) para db push/migrate
    // DATABASE_URL (porta 6543, pgBouncer) é usado apenas pelo runtime em lib/prisma.ts
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
